#!/bin/bash

# Set the directory to store the file
dir="$HOME/system/scripts/apt"
file="$dir/manual_packages"

# Search for packages and select multiple packages using fzf preview mode
selected=$(apt-cache pkgnames | fzf --multi --preview 'apt-cache show {}')

# Append the selected packages to the file if they are not already listed
while read -r pkg; do
  if ! grep -q "^$pkg\$" "$file"; then
    echo "$pkg" | tee -a "$file"
  fi
done <<<"$selected"

sort "$file" -o "$file"

if ! sudo apt update -qq; then
  echo "ERROR: couldn't update!"; exit 1
fi

if ! sudo apt upgrade -qqy; then
  echo "ERROR: couldn't upgrade!"; exit 1
fi

# Install the selected packages
if sudo apt install -qqy $selected; then
  sudo apt autoremove
else
  "ERROR: couldn't install"; exit 1
fi
