#!/bin/bash

# future batch!
if [ "$1" == 'b' ]; then
    echo "hi"; exit 0
fi

url=""

for arg in "$@"; do
    if [ ${#arg} -gt 20 ]; then
        url+="https://youtube.com/playlist?list=$arg "
    else
        url+="https://youtube.com/watch?v=$arg "
    fi
done

if [ ! -d "$HOME/music" ]; then
    mkdir "$HOME/music"
fi

/usr/bin/yt-dlp \
    --yes-playlist \
    --output "$HOME/music/%(title)s.%(ext)s" \
    --no-batch-file \
    --extract-audio \
    --download-archive "$HOME/.cache/.yt" \
    --quiet \
    "$url"